#include "primlib.h"

#ifndef SETTINGS_H
#define SETTINGS_H

#define BOARD_OFFSET_X 400

#define BOARD_WIDTH 10
#define BOARD_HEIGHT 20

#define NEXT_BLOCK_X (BOARD_WIDTH + 2)
#define NEXT_BLOCK_Y (BOARD_HEIGHT / 2)

#define PIECE_AMOUNT 7
#define FRAME_COUNTER_LIMIT 60

#define EMPTY_SPACE_VALUE 0
#define WALL_VALUE 9
#define PIECE_CENTER_VALUE 2
#define PIECE_BLOCK_VALUE 1
#define DELETED_SPACE_VALUE -1
#define PUT_BLOCK_VALUE 10

#define BLOCK_HORIZONTAL_SPEED 8


#define COLOUR


#endif
